{% set name = "cdms2" %}
{% set version = "2.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/UV-CDAT/cdms/archive/v{{ version }}.tar.gz
  sha256: 70e52a24654953c0362a6036d2d2faebaf4024145418a77453a2476ffe168612

build:
  number: 0
  skip: True  # [win or py3k] 

requirements:
  build:
    - toolchain  # [osx]
    - python
    - setuptools
    - libcdms
    - cdat_info
    - numpy x.x
    - libdrs_f
    - gcc  # [linux]
  run:
    - python
    - libcf
    - distarray
    - cdtime
    - libcdms
    - cdat_info
    - numpy x.x
    - esmf >=7
    - esmpy
    - libdrs_f
    - pyopenssl
    - libgcc  # [linux]

test:
  commands:
      - export UVCDAT_ANONYMOUS_LOG=false && python -c "import cdms2"  

about:
  home:  http://uvcdat.llnl.gov/documentation/cdms/cdms.html
  license: 'CCLRC'
  summary: 'Community Data Management System'
  description: |            
    The Community Data Management System is an object-oriented 
    data management system, specialized for organizing 
    multidimensional, gridded data used in climate 
    analysis and simulation.
  dev_url: http://github.com/UV-CDAT/cdms2

extra:
  recipe-maintainers:
    - dnadeau4
    - doutriaux1
